#!/bin/bash
echo "Please insert serial number: "
read serial_number

#convert to hexadecimal
serial_number_hexa=$(printf '%x\n' $serial_number)

#string size
size=${#serial_number_hexa}

#write only one
if [ $size -eq 1 ]
    then
        D=$(printf '%s' $serial_number_hexa | cut -c 1)
        printf "Message: 0x00 0x0%s\n" $D
elif [ $size -eq 2 ]
    then
        C=$(printf '%s' $serial_number_hexa | cut -c 1)
        D=$(printf '%s' $serial_number_hexa | cut -c 2)
        printf "Message: 0x00 0x%s%s\n" $C $D
elif [ $size -eq 3 ]
    then
        B=$(printf '%s' $serial_number_hexa | cut -c 1)
        C=$(printf '%s' $serial_number_hexa | cut -c 2)
        D=$(printf '%s' $serial_number_hexa | cut -c 3)
        printf "Message: 0x0%s 0x%s%s\n" $B $C $D
elif [ $size -eq 4 ]
    then
        A=$(printf '%s' $serial_number_hexa | cut -c 1)
        B=$(printf '%s' $serial_number_hexa | cut -c 2)
        C=$(printf '%s' $serial_number_hexa | cut -c 3)
        D=$(printf '%s' $serial_number_hexa | cut -c 4)
        printf "Message: 0x%s%s 0x%s%s\n" $A $B $C $D
else
    printf "Invalid number\n"
fi
